openapi: 3.0.1
info:
  title: Salesforce Contact API
  version: 1.0.0

servers:
  - url: https://aiactionsnodejs.onrender.com

paths:
  /custom-contact:
    get:
      operationId: getCustomContact
      summary: Get contact details using email via Apex REST
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
          description: Contact email address (e.g., user@example.com)
      responses:
        "200":
          description: Contact retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContactResponse"
        "400":
          description: Missing or invalid query parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Contact not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /create-contact:
    post:
      operationId: createContact
      summary: Create a new contact in Salesforce via Apex REST
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewContact"
      responses:
        "201":
          description: Contact created
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                  Message:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ContactResponse:
      type: object
      properties:
        Id:
          type: string
        Name:
          type: string
        Email:
          type: string
        Message:
          type: string

    NewContact:
      type: object
      required:
        - FirstName
        - LastName
        - Email
      properties:
        FirstName:
          type: string
        LastName:
          type: string
        Email:
          type: string
        Phone:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
