openapi: 3.0.1
info:
  title: Mock Salesforce Contact API
  version: 1.0.0
  description: Simple API for testing Salesforce contact retrieval, updates, and deletion

servers:
  - url: https://aiactionsnodejs.onrender.com

paths:
  /get-contacts:
    post:
      summary: Get contacts by text filter
      operationId: getContacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filter:
                  type: string
                  example: "john"
      responses:
        "200":
          description: List of matching contacts
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContactsResponse"
        "400":
          description: Missing or invalid filter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /update-contact:
    put:
      summary: Update a contact by ID
      operationId: updateContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateContactRequest"
      responses:
        "200":
          description: Contact updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Contact not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /delete-contact:
    delete:
      summary: Delete a contact by ID
      operationId: deleteContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Id
              properties:
                Id:
                  type: string
                  example: "002"
      responses:
        "200":
          description: Contact deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteResponse"
        "400":
          description: Invalid request (missing Id)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Contact not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Contact:
      type: object
      properties:
        Id:
          type: string
        FirstName:
          type: string
        LastName:
          type: string
        Email:
          type: string

    ContactsResponse:
      type: object
      properties:
        count:
          type: integer
        contacts:
          type: array
          items:
            $ref: "#/components/schemas/Contact"
        message:
          type: string

    UpdateContactRequest:
      type: object
      required:
        - Id
      properties:
        Id:
          type: string
        FirstName:
          type: string
        LastName:
          type: string
        Email:
          type: string

    UpdateResponse:
      type: object
      properties:
        message:
          type: string
        contact:
          $ref: "#/components/schemas/Contact"

    DeleteResponse:
      type: object
      properties:
        message:
          type: string
        deleted:
          $ref: "#/components/schemas/Contact"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
