openapi: 3.0.1
info:
  title: Hello Plugin
  version: 1.0.0
  description: A test plugin that returns hello.

servers:
  - url: https://aiactionsnodejs.onrender.com

paths:
  /hello:
    get:
      operationId: sayHello
      summary: Returns a hello message
      responses:
        "200":
          description: Successful hello response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from plugin!
