openapi: 3.0.1
info:
  title: Test Contact API
  version: 1.0.0
  description: Retrieve mock Salesforce contacts with optional filter.

servers:
  - url: https://aiactionsnodejs.onrender.com

paths:
  /get-contacts:
    get:
      operationId: getTestContacts
      summary: Get filtered mock contacts
      parameters:
        - in: query
          name: filter
          schema:
            type: string
          required: false
          description: Optional name filter (e.g. John)
      responses:
        "200":
          description: A filtered list of contacts
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  contacts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Contact"

components:
  schemas:
    Contact:
      type: object
      properties:
        Id:
          type: string
        FirstName:
          type: string
        LastName:
          type: string
        Email:
          type: string
