openapi: 3.0.1
info:
  title: Salesforce Contact API (Test)
  version: 1.0.0
  description: Returns test contacts from a mock API.

servers:
  - url: https://aiactionsnodejs.onrender.com

paths:
  /get-contacts:
    get:
      operationId: getTestContacts
      summary: Get mock contact list
      responses:
        "200":
          description: Returns an array of test contacts
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Contact"

components:
  schemas:
    Contact:
      type: object
      properties:
        Id:
          type: string
        FirstName:
          type: string
        LastName:
          type: string
        Email:
          type: string
